CREATE TABLE CLIENTS(
    ID_CLIENTS BIGSERIAL NOT NULL CONSTRAINT PK_CLIENT PRIMARY KEY,
    LOGIN TEXT NOT NULL UNIQUE,
    PASSWORD TEXT NOT NULL,
    EMAIL TEXT NOT NULL UNIQUE
);

CREATE TABLE PRODUCTS(
    ID_PRODUCTS BIGSERIAL NOT NULL CONSTRAINT PK_PRODUCTS PRIMARY KEY,
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    QUANTITY INT NOT NULL,
    PRICE INT NOT NULL
);

CREATE TABLE ORDER_HISTORY(
    ID_ORDER_HISTORY BIGSERIAL NOT NULL CONSTRAINT PK_ORDER_HISTORY PRIMARY KEY,
    CLIENT_LOGIN TEXT NOT NULL,
    PRODUCTS_NAME TEXT NOT NULL,
    ADDRESS TEXT NOT NULL
);

INSERT INTO PRODUCTS (NAME, DESCRIPTION, QUANTITY, PRICE) VALUES
('Швабра', 'Прекрасная швабра',100, 1000),
('Ведро', 'Прекрасное ведро', 99, 500);